### ISSUE TITLE
Dropdown field deforms when navigating using Tab key

### ISSUE THREAD

**Issue by gurucomkz** [silverstripe/silverstripe-admin#1127]
Using `silverstripe/recipe-cms` `4.6.1@stable`
Scenario:
* Open Security -> any user account.
* Put cursor to the input that precedes the "Interface Language"
* Press "Tab" several times to navigate to the input that comes after the "Interface Language"
Result:
<img width="850" alt="Screen Shot 2020-09-30 at 16 02 05" src="https://user-images.githubusercontent.com/12028675/94638374-4bd06d00-0336-11eb-8031-66b0203b8050.png">

This happened to all of our projects, to all of the dropdown fields.

I tracked it down to `client/src/styles/_chosen.scss`:
```scss
// Avoid chosen dropdowns overflowing when not active
.chosen-container:not(.chosen-container-active) {
  overflow: hidden;
}
```

This rule messes up the display and I can't find a case this one is actually useful any more.
