### ISSUE TITLE
1.12 horizontal scrollbar in split mode

### ISSUE THREAD

**Issue by tiller1010** [silverstripe/silverstripe-admin#1430]
This PR removed a style rule that prevented horizontal scrollbars when in split mode:
https://github.com/silverstripe/silverstripe-admin/pull/1422

The scrollbar **does not** show in Firefox, but it does show in Brave and Edge.

### Firefox
![firefox](https://user-images.githubusercontent.com/42498429/211030221-5fbece45-f58b-4aa2-bdaf-518f9fa61c0d.png)

### Brave
![brave](https://user-images.githubusercontent.com/42498429/211030224-0a55e163-6173-42d0-be7d-881adbe672c1.png)

### Edge
![edge](https://user-images.githubusercontent.com/42498429/211030227-a12a161b-734d-43a3-818e-81a3fff804a8.png)

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1629

**Comment by StevenLantinga** [comment]
For anybody wondering: This is caused by the mode dropdown itself in the right bottom. Adding `#preview-mode-dropdown-in-content .chosen-drop { right: 0; width: 160px; }` fixed the issue.

**Comment by RVXD** [comment]
I guess this would be a minor change to fix? Issue has been open since jan 6. Is there any way I can help?
One note: the issue is also visible in non-split mode, so maybe change title of issue.

**Comment by lerni** [comment]
Use :fire::fox_face::exclamation: :grinning:
To make the suggested fix above also work in preview-mode, I figured
```css
/* in 5.x we need to revert #7b430d4 and add the previous snippet bellow
https://github.com/silverstripe/silverstripe-admin/commit/7b430d4171da9608918190109b85e15260e0d626 */
.chosen-container:not(.chosen-container-active) {
	overflow: hidden;
}

.preview-mode-selector .chosen-drop {
	width: inherit;
	right: 0;
}
```
If that looks acceptable I would try do make build-env working, PR and also test it a bit more. To what branch:question: If 4.x, is build than done on up-merge for 5?
