### ISSUE TITLE
Dropdown item with tag <a> and class '.dropdown-item' has incorrect applied styles

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-admin#1475]
## Description
Related to https://github.com/silverstripe/silverstripe-admin/pull/1424
When working with a GridField list, when clicking on the "Edit" button in the dropdown menu, the button has the wrong (blue) colour instead of grey. When hovering and clicking, the colour does not change. This only applies to the "Edit" button in GridField list. Other buttons in the dropdown menus do not have this drawback.
With a little study of this problem, it is clear that this button has an `<a>` tag, unlike all other buttons located next to the "Edit" button, which have a `<button>` tag. Because of this, the styles of the parent element class `.ui-widget-content a`, which are specific to the `<a>` tag, are applied to this button.
```css
.ui-widget-content a, .ui-widget a, .ui-widget.ui-widget-content a {
    color: #0071c4;
}
```
instead
```css
.dropdown-item {
    display: block;
    width: 100%;
    padding: 0.45rem 1.3rem;
    clear: both;
    font-weight: 400;
    color: #43536d;
    text-align: inherit;
    white-space: nowrap;
    background-color: rgba(0,0,0,0);
    border: 0;
}
``` 
![screencapture-localhost-88-admin-security-2023-03-16-14_52_24.png](https://images.zenhubusercontent.com/6240ee9a7a0aac6d45cfd39d/6bce55a3-0287-4c48-9703-185aef541d34)

![screencapture-localhost-88-admin-security-2023-03-16-14_53_35.png](https://images.zenhubusercontent.com/6240ee9a7a0aac6d45cfd39d/040eef9e-aa14-4261-82fe-a72775ad01b5)

## AC's
- [x] Button has correct colour `#43536d` on inactive state
- [x] Button has correct colour `#ffffff` on active state

##### CMS4
- https://github.com/silverstripe/silverstripe-admin/pull/1486
##### CMS5
- https://github.com/silverstripe/silverstripe-admin/pull/1485

### Note 
- [Specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) is the algorithm used by browsers to determine the CSS declaration that is the most relevant to an element.
