### ISSUE TITLE
Sudo mode configuration doesn't work in profile controller

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-admin#1929]
### Module version(s) affected

5.4.0

### Description

Tried to turn off sudo mode for non-prod environments but the UI of the profile controller specifically doesn't seem to take this into account.

```yaml
---
Name: app-member-access
Except:
  environment: 'live'
---
# Disable sudo mode for non-prod environments as this check is not necessary (not needed for private environments)
SilverStripe\Security\Member:
  require_sudo_mode: false
```

```php
$t = Member::config()->get('require_sudo_mode');
var_export($t); // outputs false
```

![Image](https://github.com/user-attachments/assets/5d3f3a50-c6db-449e-ac58-8c30f83ddb48)

### How to reproduce

Use the provided code snippet to reproduce the issue.

### Validations

- [x] Check that there isn't already an issue that reports the same bug
- [x] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs

- https://github.com/silverstripe/silverstripe-admin/pull/1930
- https://github.com/silverstripe/silverstripe-admin/pull/1931
