### ISSUE TITLE
Changing the admin URL causes a 500 error on the default route

### ISSUE THREAD

**Issue by DorsetDigital** [silverstripe/silverstripe-admin#689]
Tested on Silverstripe 4.1.1 and 4.2.1

When changing the admin route by adding the following YML (as per the docs):

```YAML
---
Name: myadmin
After:
- '#adminroutes'
---
SilverStripe\Control\Director:
  rules:
    'admin': ''
    'cms': 'SilverStripe\Admin\AdminRootController'
```

The new URL becomes active and works correctly.  The old URL (eg.  example.com/admin) now throws a 500 error (below).   I would expect it to return a 404.

``` 
Uncaught InvalidArgumentException: Missing spec class
GET /admin
Line 403 in /app/vendor/silverstripe/framework/src/Core/Injector/Injector.php
```
The full stack trace is attached.
[admin_error_trace.txt](https://github.com/silverstripe/silverstripe-admin/files/2482545/admin_error_trace.txt)
