### ISSUE TITLE
Can't access dropdowns within accordion areas

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#779]
When trying to access select dropdown options from within a accordion the options get cut off, without a visible way of selecting an option.

Ideally we would either be able to extend the accordion area to show options, or the select dropdown could extend outside of the accordion area.

![image](https://user-images.githubusercontent.com/555033/49776500-1cb3ca80-fd61-11e8-8ce1-d3e022993084.png)

## Acceptance criteria
- ToggleCompositeField does not cut off the content of common form field likes DropDownField or LinkField.

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1719
- https://github.com/silverstripe/silverstripe-admin/pull/1720

**Comment by sachajudd** [comment]
I seem to be able to still reproduce this issue on 4.3 @ScopeyNZ

**Comment by michalkleiner** [comment]
And `4.4.1` and/or `4.4.x-dev`?

**Comment by sachajudd** [comment]
Yup sorry, forgot to include latest versions.

**Comment by kinglozzer** [comment]
Our workaround for this at the moment is to set `overflow: visible`, but reset it to `overflow: hidden` during the transition (otherwise the content immediately appears while the container is still animating its height)

```css
.ss-toggle .ui-accordion-content[aria-expanded=true] {
	overflow: visible !important;
}

.ss-toggle .ui-accordion-content[aria-expanded=true][style*="height"] {
	overflow: hidden !important;
}
```
